import type { Prisma } from '@prisma/client';

/** Ações auditadas do sistema (expandidas nas próximas fases). */
export const AuditAction = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_BLOCKED_INACTIVE: 'AUTH_LOGIN_BLOCKED_INACTIVE',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_ACTIVATED: 'SUPPLIER_ACTIVATED',
  SUPPLIER_DEACTIVATED: 'SUPPLIER_DEACTIVATED',
  ACTION_TYPE_CREATED: 'ACTION_TYPE_CREATED',
  ACTION_TYPE_UPDATED: 'ACTION_TYPE_UPDATED',
  ACTION_TYPE_ACTIVATED: 'ACTION_TYPE_ACTIVATED',
  ACTION_TYPE_DEACTIVATED: 'ACTION_TYPE_DEACTIVATED',
  RECEIPT_METHOD_CREATED: 'RECEIPT_METHOD_CREATED',
  RECEIPT_METHOD_UPDATED: 'RECEIPT_METHOD_UPDATED',
  RECEIPT_METHOD_ACTIVATED: 'RECEIPT_METHOD_ACTIVATED',
  RECEIPT_METHOD_DEACTIVATED: 'RECEIPT_METHOD_DEACTIVATED',
  RECEIVABLE_CREATED: 'RECEIVABLE_CREATED',
  RECEIVABLE_UPDATED: 'RECEIVABLE_UPDATED',
  RECEIVABLE_CANCELED: 'RECEIVABLE_CANCELED',
  RECEIPT_CREATED: 'RECEIPT_CREATED',
  RECEIPT_UPDATED: 'RECEIPT_UPDATED',
  RECEIPT_CONFIRMED: 'RECEIPT_CONFIRMED',
  RECEIPT_REVERSED: 'RECEIPT_REVERSED',
  CURRENT_ACCOUNT_CREATED: 'CURRENT_ACCOUNT_CREATED',
  CURRENT_ACCOUNT_UPDATED: 'CURRENT_ACCOUNT_UPDATED',
  CURRENT_ACCOUNT_ACTIVATED: 'CURRENT_ACCOUNT_ACTIVATED',
  CURRENT_ACCOUNT_DEACTIVATED: 'CURRENT_ACCOUNT_DEACTIVATED',
  CURRENT_ACCOUNT_SHARED: 'CURRENT_ACCOUNT_SHARED',
  CURRENT_ACCOUNT_ENTRY_CREATED: 'CURRENT_ACCOUNT_ENTRY_CREATED',
  CURRENT_ACCOUNT_EXIT_CREATED: 'CURRENT_ACCOUNT_EXIT_CREATED',
  CURRENT_ACCOUNT_ADJUSTMENT_CREATED: 'CURRENT_ACCOUNT_ADJUSTMENT_CREATED',
  CURRENT_ACCOUNT_MOVEMENT_REVERSED: 'CURRENT_ACCOUNT_MOVEMENT_REVERSED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntity = {
  USER: 'User',
  AUTH: 'Auth',
  SUPPLIER: 'Supplier',
  ACTION_TYPE: 'ActionType',
  RECEIPT_METHOD: 'ReceiptMethod',
  RECEIVABLE: 'Receivable',
  RECEIPT: 'ReceivableReceipt',
  CURRENT_ACCOUNT: 'CurrentAccount',
  CURRENT_ACCOUNT_USER: 'CurrentAccountUser',
  CURRENT_ACCOUNT_MOVEMENT: 'CurrentAccountMovement',
} as const;

/** Contexto do ator que executa a ação (preenchido pelos controllers). */
export interface ActorContext {
  userId?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
}

export interface AuditLogInput {
  userId?: string | null;
  action: string;
  entityType: string;
  entityId?: string | null;
  oldValues?: Prisma.InputJsonValue | null;
  newValues?: Prisma.InputJsonValue | null;
  reason?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
}
